version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../src:/usr/src/app
    command: sh -c "yarn start"
    ports:
      - "3000:3000"
    stdin_open: true